{{-- NOTE: GENERATED BY GULP !!! --}}<?php
$b = "block-name"; // To be used inside HTML

// Start: Class name automation
  $b__for_css = ".".$b; // To be used inside CSS
  $b__uniq = $b."--".mt_rand(1, 999); // To be used inside HTML
  $b__uniq_for_css = ".".$b__uniq; // To be used inside CSS
// End: Class name automation

?>
@extends('layout.block', [
  "block_classes" => "", // Will be added to main block div. e.g. flo-block--full-width
  // "data_onready" => "block_name" // Specify a function (see _blank.js on how to define) that will be executed on document ready.
])

@section('block_content')
  @include('core.style', [
    "breakpoint__general" => "

      ".
      flo_render_typography_styles(
      $b__uniq_for_css." ".$b__for_css."__element-name",
      flo_data($data, "title-font", false)
      )
      ."

      ".$b__uniq_for_css." ".$b__for_css."__element-name {

      }

    "
  ])
  <div class="{{$b}} {{$b__uniq}}">



  </div>

@overwrite
