{{-- NOTE: GENERATED BY GULP !!! --}}<?php
$b = "flo-block-text-block-2"; // To be used inside HTML

// Start: Class name automation
  $b__for_css = ".".$b; // To be used inside CSS
  $b__uniq = $b."--".mt_rand(1, 999); // To be used inside HTML
  $b__uniq_for_css = ".".$b__uniq; // To be used inside CSS
// End: Class name automation

$text_content = flo_data($data, "text_content");
$text_color = flo_data($data, "text_color");
$text_font = flo_data($data, "text_font");

?>
@extends('layout.block', [
  "block_classes" => "", // Will be added to main block div. e.g. flo-block--full-width
  // "data_onready" => "block_name" // Specify a function (see _blank.js on how to define) that will be executed on document ready.
])
@include('core.style', [
  "breakpoint__general" => "

    ".
    flo_render_typography_styles(
    $b__uniq_for_css." ".$b__for_css."__text-content",
    $text_font
    )
    ."

    ".$b__uniq_for_css." {
      color: ".$text_color.";
    }

  "
])
@section('block_content')
  <div class="{{$b}} {{$b__uniq}}">
    <div class="{{$b}}__text-content">{{$text_content}}</div>
  </div>
@overwrite
