{{-- NOTE: GENERATED BY GULP !!! --}}<?php
  wp_nav_menu(
    array(
      "container_class" => $b . "__menu-wrap flo-generic-menu-wrap",
      "menu_class" => $b . "__menu flo-generic-menu-wrap__menu",
      "theme_location" => "primary"
    )
  );
?>
