{{-- NOTE: GENERATED BY GULP !!! --}}<div class="flo-video-embed">

  <div class="flo-video-embed__screen" data-flo-video-embed-embed-code="{{ htmlentities($embed_code) }}">

  </div>
  <div class="flo-video-embed__video-button">
    <i class="flo-video-embed__video-button-icon flo-video-embed__video-button-icon--play flo-icon-play"></i>
    <i class="flo-video-embed__video-button-icon flo-video-embed__video-button-icon--stop flo-icon-close"></i>
  </div>

</div>
