<?php /* NOTE: GENERATED BY GULP */ $default_theme_fonts = array(

'special_heading_1' => array(
  'font_family' => 'font_1_bold', // font_family
  'font_style_name' => 'Special Heading 1',
  'font_size' => 30,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.2,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'special_heading_2' => array(
  'font_family' => 'font_1_regular', // font_family
  'font_style_name' => 'Special Heading 2',
  'font_size' => 24,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.25,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'special_heading_3' => array(
  'font_family' => 'font_2_regular', // font_family
  'font_style_name' => 'Special Heading 3',
  'font_size' => 30,
  'word_spacing' => 0,
  'letter_spacing' => 0.35,
  'line_height' => 1.2,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'heading_1' => array(
  'font_family' => 'font_4_regular', // font_family
  'font_style_name' => 'Heading 1',
  'font_size' => 36,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.25,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'heading_2' => array(
  'font_family' => 'font_4_regular', // font_family
  'font_style_name' => 'Heading 2',
  'font_size' => 30,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.2,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'heading_3' => array(
  'font_family' => 'font_4_regular', // font_family
  'font_style_name' => 'Heading 3',
  'font_size' => 24,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.25,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'meta_1' => array(
  'font_family' => 'font_3_regular', // font_family
  'font_style_name' => 'Meta 1',
  'font_size' => 12,
  'word_spacing' => 0,
  'letter_spacing' => 0.3,
  'line_height' => 1.5,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'meta_2' => array(
  'font_family' => 'font_5_regular', // font_family
  'font_style_name' => 'Meta 2',
  'font_size' => 10,
  'word_spacing' => 0,
  'letter_spacing' => 0.3,
  'line_height' => 1.8,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'meta_3' => array(
  'font_family' => 'font_5_regular', // font_family
  'font_style_name' => 'Meta 3',
  'font_size' => 11,
  'word_spacing' => 0,
  'letter_spacing' => 0.2,
  'line_height' => 1.63,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'paragraph_1' => array(
  'font_family' => 'font_5_regular', // font_family
  'font_style_name' => 'Paragraph 1',
  'font_size' => 14,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.625,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'paragraph_1_link' => array(
  'font_family' => 'font_5_regular', // font_family
  'font_style_name' => 'Paragraph 1 Link',
  'font_size' => 16,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.625,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 1,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'label_1' => array(
  'font_family' => 'font_5_regular', // font_family
  'font_style_name' => 'Label 1',
  'font_size' => 11,
  'word_spacing' => 0,
  'letter_spacing' => 0.05,
  'line_height' => 1.4,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'call_to_action_1' => array(
  'font_family' => 'font_6_bold', // font_family
  'font_style_name' => 'Call to Action 1',
  'font_size' => 11,
  'word_spacing' => 0,
  'letter_spacing' => 0.3,
  'line_height' => 2.18,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'call_to_action_2' => array(
  'font_family' => 'font_6_bold', // font_family
  'font_style_name' => 'Call to Action 2',
  'font_size' => 11,
  'word_spacing' => 0,
  'letter_spacing' => 0.3,
  'line_height' => 1.63,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 1,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

'quote' => array(
  'font_family' => 'font_4_italic', // font_family
  'font_style_name' => 'Quote',
  'font_size' => 20,
  'word_spacing' => 0,
  'letter_spacing' => 0,
  'line_height' => 1.45,
  'default' => array(
    'font_color' => $color_black,
    'font_accent' => array(
      'bold' => 0,
      'italic' => 0,
      'underline' => 0,
    ),
    'font_case' => 'none', //'none','uppercase','lowercase'
  ),
  'hover_state' => array(
    ),
  'active' => array(
  ),
),

/* START: CONTENT TYPOGRAPHY */

  'heading_4' => array(
    'font_family' => 'font_4_regular', // font_family
    'font_style_name' => 'Heading 4',
    'font_size' => 21,
    'word_spacing' => 0,
    'letter_spacing' => 0,
    'line_height' => 1.25,
    'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
        'bold' => 0,
        'italic' => 0,
        'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'
    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),

  'heading_5' => array(
    'font_family' => 'font_4_regular', // font_family
    'font_style_name' => 'Heading 4',
    'font_size' => 18,
    'word_spacing' => 0,
    'letter_spacing' => 0,
    'line_height' => 1.25,
    'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
        'bold' => 0,
        'italic' => 0,
        'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'
    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),

  'heading_6' => array(
    'font_family' => 'font_4_regular', // font_family
    'font_style_name' => 'Heading 4',
    'font_size' => 14,
    'word_spacing' => 0,
    'letter_spacing' => 0,
    'line_height' => 1.25,
    'default' => array(
      'font_color' => $color_black,
      'font_accent' => array(
        'bold' => 0,
        'italic' => 0,
        'underline' => 0,
      ),
      'font_case' => 'none', //'none','uppercase','lowercase'
    ),
    'hover_state' => array(
      ),
    'active' => array(
    ),
  ),

/* END: CONTENT TYPOGRAPHY */


); ?>